# This Source Code Form is licensed MPLv2: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

#language: cpp

os:       linux
dist:     xenial
language: generic
services: docker

install: |
  touch "~/cache/stamp-$TRAVIS_BUILD_ID-$TRAVIS_BUILD_NUMBER-git$TRAVIS_COMMIT-$TRAVIS_JOB_ID-$TRAVIS_JOB_NUMBER" && ls -l ~/cache/
before_cache: |
  (cd ~/cache/ && pwd && ls -l)

jobs:
  include:

    - stage: Stage1
      env: PIPELINE=clang
      name: " clang-1 (extra characters) / more text"
      script: |
        pwd &&
        echo './autogen.sh --prefix=/usr CC=clang CXX=clang++' >TEST

    - stage: Stage2
      env: PIPELINE=clang
      name: Job name with extra info
      script: |
        pwd &&
        egrep clang TEST

    - stage: Stage1
      env: PIPELINE=barzonk
      script: |
        echo Deploy and upload...
      name: Barzonk-1   # comments after name

cache:
  directories:
    - ~/cache/

notifications:
  irc: false
  email: false
