# This Source Code Form is licensed MPLv2: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

#language: cpp

os:       linux
dist:     xenial
language: generic
services: docker

jobs:
  include:

    - stage: Stage1
      env: PIPELINE=clang
      name: clang-1
      before_install: |
        uname -a && pwd && echo nproc=`nproc` &&
        rm -v -rf ~/cache/* &&
        touch ~/cache/Stage1-$PIPELINE && ls -l ~/cache/ &&
        cd ~ && git clone --branch=master https://github.com/tim-janik/beast.git && cd beast
      script: |
        pwd &&
        echo './autogen.sh --prefix=/usr CC=clang CXX=clang++' >TEST
      before_cache: >
        cd ~/cache/ && mv -v ~/beast/ .

    - stage: Stage2
      name: clang-2
      env: PIPELINE=clang
      before_install:
        - touch ~/cache/Stage2-$PIPELINE && ls -l ~/cache/
        - mv -v ~/cache/beast/ ~ && cd ~/beast/
      script:
        - pwd
        - egrep clang TEST

    - stage: Stage1
      env: PIPELINE=barzonk
      install:
        - touch ~/cache/Deploy-$PIPELINE && ls -l ~/cache/
      script:
        - echo Deploy and upload...
        - ls -l ~/cache/
      name: barzonk-1

cache:
  directories:
    - ~/cache/

notifications:
  irc: false
  email: false
