# This Source Code Form is licensed MPLv2: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

#language: cpp

os: linux
dist: xenial
language: generic
services: docker
sudo: false   # http://docs.travis-ci.com/user/workers/container-based-infrastructure/ (required: needed for apt-get)
compiler:
  - gcc
  - clang

cache:
  directories:
    - ~/cache/

matrix:
  fast_finish: true

addons:
  apt:
    sources: # https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
      - ubuntu-toolchain-r-test
    packages: [
      # g++ >= 4.8 is required for -std=c++11
      # gcc-5, g++-5,
      ]


install:
  - git clean -f

before_script:
  - true # make

script:
  - true # make check

after_success:
  - echo "Done, build OK!"

jobs:
    include:
    - stage: PrepareCI
      before_install:
        - uname -a
        - cat /etc/lsb-release
        - pwd
        - free -tm
        - df -h
        - docker --version
        - make --version
        - autoconf --version
        - automake --version
        - python --version
        - flex --version
        - bison --version
        - dpkg --get-selections
      install:
        - ls -al ~/cache/ || true
        - mkdir -p ~/cache/
        - find ~/cache/ -type f -mtime +1 -delete
      script:
        - time DIMG='timjanik/ci-cache:bionic-180930' &&
          docker pull $DIMG &&
          docker tag $DIMG $TRAVIS_COMMIT
        - time docker save $TRAVIS_COMMIT |
          bzip2 -9 > ~/cache/dimg-$TRAVIS_COMMIT.tbz
    - stage: Test2
      script:
        - echo test2
        - time docker load -i ~/cache/dimg-$TRAVIS_COMMIT.tbz
        - time docker pull $TRAVIS_COMMIT
    - stage: Deploy
      install:
        - time docker load -i ~/cache/dimg-$TRAVIS_COMMIT.tbz
      script:
        - echo deploy
        - time docker pull $TRAVIS_COMMIT

notifications:
  irc: false
  email: false
