# This Source Code Form is licensed MPLv2: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

#language: cpp

os:       linux
dist:     xenial
language: generic
services: docker

jobs:
  include:

    - stage: Stage1
      env: PIPELINE=clang
      name: " clang-1 (extra characters) / more text"
      before_install: |
        uname -a && pwd && echo nproc=`nproc` && rm -v -rf ~/cache/* &&
        cd ~ && git clone --branch=master https://github.com/tim-janik/beast.git &&
        touch ~/cache/"$PIPELINE-$TRAVIS_BUILD_STAGE_NAME" && ls -l ~/cache/ && cd ~/beast/
      script: |
        pwd &&
        echo './autogen.sh --prefix=/usr CC=clang CXX=clang++' >TEST
      before_cache: >
        cd ~/cache/ && mv -v ~/beast/ .

    - stage: Stage2
      name: clang-2 with extra info
      env: PIPELINE=clang
      before_install: |
        mv -v ~/cache/beast/ ~ && cd ~/beast/ &&
        touch ~/cache/"$PIPELINE-$TRAVIS_BUILD_STAGE_NAME" && ls -l ~/cache/ && cd ~/beast/
      script:
        - pwd
        - egrep clang TEST

    - stage: Stage1
      env: PIPELINE=barzonk
      before_install: |
        touch ~/cache/"$PIPELINE-$TRAVIS_BUILD_STAGE_NAME" && ls -l ~/cache/ && cd ~/beast/
      script:
        - echo Deploy and upload...
        - ls -l ~/cache/
      name: Barzonk-1 # comments after name

cache:
  directories:
    - ~/cache/

notifications:
  irc: false
  email: false
