on: # on: [push]
  push:
    branches:    
      - master         # Push events on master branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        repository: tim-janik/beast
        ref: refs/heads/master
    - run: pwd
    - run: ls -l
    - run: find / -name bse
    #    ./version.sh
    #    misc/cibuild.sh quick all check
