on: # on: [push]
  push:
    branches:    
      - master         # Push events on master branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        repository: tim-janik/beast
    - run: |
        pwd
        ls -l ./version.sh
        ./version.sh
        misc/cibuild.sh quick all check
