on: # on: [push]
  push:
    branches:    
      - master         # Push events on master branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        repository: tim-janik/beast
        ref: refs/heads/master
    - run: |
        pwd
        cd ../beast
        ./version.sh
        sed 's/ -ti/ -t/' -i misc/cibuild.sh 
        misc/cibuild.sh quick all check
